Merging

In [1]:
import pandas as pd

data1 = [[1, 'Raj', 25], 
         [2, 'Sharma', 42], 
         [3, 'Saroj', 22], 
         [4, 'Raja', 51], 
         [5, 'Kajal', 26]]
df1 = pd.DataFrame(data1, columns=['ID', 'Name', 'Age'])

data2 = [[1, 'Male', 25000], 
         [2, 'Male', 42500], 
         [3, 'Female', 22300], 
         [4, 'Male', 51400], 
         [5, 'Female', 26800]]
df2 = pd.DataFrame(data2, columns=['ID', 'Gender', 'Salary'])

print("DataFrame 1:")
print(df1)
print("\nDataFrame 2:")
print(df2)

DataFrame 1:
   ID    Name  Age
0   1     Raj   25
1   2  Sharma   42
2   3   Saroj   22
3   4    Raja   51
4   5   Kajal   26

DataFrame 2:
   ID  Gender  Salary
0   1    Male   25000
1   2    Male   42500
2   3  Female   22300
3   4    Male   51400
4   5  Female   26800

Inner merge

In [2]:
merged_df = pd.merge(df1, df2, on='ID', how='inner')
print(merged_df)

   ID    Name  Age  Gender  Salary
0   1     Raj   25    Male   25000
1   2  Sharma   42    Male   42500
2   3   Saroj   22  Female   22300
3   4    Raja   51    Male   51400
4   5   Kajal   26  Female   26800

Left merge

In [3]:
merged_df = pd.merge(df1, df2, on='ID', how='left')
print(merged_df)

   ID    Name  Age  Gender  Salary
0   1     Raj   25    Male   25000
1   2  Sharma   42    Male   42500
2   3   Saroj   22  Female   22300
3   4    Raja   51    Male   51400
4   5   Kajal   26  Female   26800

Right merge

In [4]:
merged_df = pd.merge(df1, df2, on='ID', how='right')
print(merged_df)

   ID    Name  Age  Gender  Salary
0   1     Raj   25    Male   25000
1   2  Sharma   42    Male   42500
2   3   Saroj   22  Female   22300
3   4    Raja   51    Male   51400
4   5   Kajal   26  Female   26800

Outer merge

In [5]:
merged_df = pd.merge(df1, df2, on='ID', how='outer')
print(merged_df)

   ID    Name  Age  Gender  Salary
0   1     Raj   25    Male   25000
1   2  Sharma   42    Male   42500
2   3   Saroj   22  Female   22300
3   4    Raja   51    Male   51400
4   5   Kajal   26  Female   26800

Merging on multiple columns

In [6]:
df1['Country'] = ['USA', 'Canada', 'USA', 'Canada', 'USA']
df2['Country'] = ['USA', 'Canada', 'USA', 'Canada', 'Mexico']

merged_df = pd.merge(df1, df2, on=['ID', 'Country'], how='inner')
print(merged_df)

   ID    Name  Age Country  Gender  Salary
0   1     Raj   25     USA    Male   25000
1   2  Sharma   42  Canada    Male   42500
2   3   Saroj   22     USA  Female   22300
3   4    Raja   51  Canada    Male   51400

merging with different column names

In [7]:
df2.rename(columns={'ID': 'EmployeeID'}, inplace=True)

merged_df = pd.merge(df1, df2, left_on='ID', right_on='EmployeeID', how='inner')
print(merged_df)

   ID    Name  Age Country_x  EmployeeID  Gender  Salary Country_y
0   1     Raj   25       USA           1    Male   25000       USA
1   2  Sharma   42    Canada           2    Male   42500    Canada
2   3   Saroj   22       USA           3  Female   22300       USA
3   4    Raja   51    Canada           4    Male   51400    Canada
4   5   Kajal   26       USA           5  Female   26800    Mexico

creating sample dataframe

In [8]:
import pandas as pd

# creating a dataframe
df = pd.DataFrame({'A': ['John', 'Boby', 'Mina'],
                   'B': ['Masters', 'Graduate', 'Graduate'],
                   'C': [27, 23, 21]})

df

      A         B   C
0  John   Masters  27
1  Boby  Graduate  23
2  Mina  Graduate  21

creating and pivot a dataframe

In [9]:
df.pivot_table(index='A', columns='B', values='C', aggfunc='mean')

B     Graduate  Masters
A
Boby      23.0      NaN
John       NaN     27.0
Mina      21.0      NaN

multilevel pivot table with Pandas DataFrame

In [10]:
df.pivot(index='A', columns='B', values=['C', 'A'])

            C                A
B    Graduate Masters Graduate Masters
A
Boby       23     NaN     Boby     NaN
John      NaN      27      NaN    John
Mina       21     NaN     Mina     NaN

valuerror raised in pivoting a dataframe

In [11]:
import pandas as pd

df = pd.DataFrame({'A': ['John', 'John', 'Mina'],
                   'B': ['Masters', 'Masters', 'Graduate'],
                   'C': [27, 23, 21]})


df.drop_duplicates(subset=['A', 'B']).pivot(index='A', columns='B', values='C')

B     Graduate  Masters
A
John       NaN     27.0
Mina      21.0      NaN